### ISSUE TITLE
How to handle error ?

### ISSUE THREAD

**Issue by maxired** [amaurymartiny/now-middleware#25]
Hi, 
I was trying to use your project to plug some authentication middleware.

I am trying to implement what in express would be done with
```javascript
app.use(function (err, req, res, next) {
      if (err.name === 'UnauthorizedError') {
        res.status(401).send('invalid token...');
      }
    });
```

It looks like this is not possible currently.

**Comment by amaurymartiny** [comment]
Ah yeah, not yet. Though it wouldn't be too hard to add it.

Would you like to give a shot with a PR?
