### ISSUE TITLE
Move `express` and `@types/express` to `devDependencies` instead

### ISSUE THREAD

**Issue by micalevisk** [amaurymartiny/now-middleware#66]
https://github.com/amaurymartiny/now-middleware/blob/4961bcab275dfa9570e1345ebce60a691f9f5e7f/package.json#L21-L24

https://github.com/amaurymartiny/now-middleware/blob/7eab0bb1c2f54f87cc56c883e0ad6cfdcba2bc67/src/chain.ts#L18-L24

since you're only importing types from `express`, you can move this dependency to devDependencies right? Am I missing something? same with `@types/express`

**Comment by amaurymartiny** [comment]
Sounds good to me!

The best would be to add to devDependencies + peerDependencies. Would you like to create a PR?

**Comment by micalevisk** [comment]
for sure!

Why should we add `express` to peerDependencies? I didn't get that :confused: 

and also, I'll change `src/chain.ts` to use [`import type { ... } from 'express'`](https://www.typescriptlang.org/docs/handbook/modules.html#importing-types) TS syntax.

ty.

**Comment by amaurymartiny** [comment]
> Why should we add express to peerDependencies? I didn't get that 😕

So that if a someone installs `now-middleware` without installing `express`, a warning will be shown on npm/yarn.

**Comment by amaurymartiny** [comment]
Published in v0.2.1.
